# Site settings
title: 简谈
SEOTitle: simplytoc | pages
header-img: img/home-bg.jpg
email: huangyangh2004@gmail.com
description: "一路蹒跚前行"
keyword: ""
url: "https://icyhy.github.io"              # GitHub Pages 用户站点根域名
baseurl: "/simplytoc"         # 项目页的子路径（仓库名）



# SNS settings
RSS: true
weibo_username:     1025895004
zhihu_username:     icyhy
github_username:    icyhy
#twitter_username:  icyhy
facebook_username:  icyhy



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor","Gemfile","Gemfile.lock",".bundle"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Plugins
# 从 Jekyll 3.0 起，配置项由 `gems` 重命名为 `plugins`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: icyhy
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "大侃",
        href: "https://gitee.com/xknife"
    },{
        title: "克瑞普斯豆",
        href: "http://cripps.gitee.io/"
    },{
        title: "丙",
        href: "#"
    },{
        title: "丁",
        href: "#"
    }
]